### ISSUE TITLE
Autotype cuts off last character of the username and inserts it into the password field

### ISSUE THREAD

**Issue by dextersgenius** [MacPass/MacPass#1023]
**Describe the bug**
Autotype cuts off last character of the username and inserts it into the password field
Eg: 
Usernam {TAB} ePassword {ENTER}
This of course causes logins to fail. 

**To Reproduce**
1. Select an entry with username/password to autotype
2. Press the hotkey to trigger autotype (Command+T)

**Expected behavior**
Username and password should be typed correctly

**Desktop (please complete the following information):**
 - macOS: Catalina 10.15.2
 - Version 0.7.10

**Edit**: I have to say that this bug isn't present in KeePassXC using the same kbdx file, entry and target windows. One difference I've noticed is that KeePassXC types a bit slower whereas MacPass seems to type instantly, maybe that's the cause of the issues? My target window is a remote windows desktop inside Citrix Workspace, so could be that the input is too fast for Citrix to process correctly.

**Comment by mstarke** [comment]
If you input is indeed too fast, you can try to add {DELAY=100} in front of you Autotype sequence to add a 100ms delay for each entry. I did think about adding a global delay for Autotyping to the preferences but since this is sometimes only needed for single items in the list I prefer the custom solution of adding it via the {DELAY=<timeInMilliseconds>} command.

**Comment by mstarke** [comment]
@dextersgenius  Did you get anything to work by adding the delay?

**Comment by mstarke** [comment]
I'm closing this since the solution to add a global delay should work in this special scenario
