### ISSUE TITLE
Autotype - Custom Window Associations not sticking

### ISSUE THREAD

**Issue by 88-percent** [MacPass/MacPass#1052]
Is is just me or are custom window associations not sticking?

I can create a custom window association by selecting the entry then 

autotype > window associations > + 

and entering the window title. 

The association works perfectly with Global Autotype until the database is closed. Upon unlocking the database the Global hotkey no longer works and, upon inspection, the window associations list is blank.

No other instances of data loss in the database.

MacPass 0.7.11 (23550)
MacOS 10.13.6

**Comment by mstarke** [comment]
Do you by any chance store the database as KDB? If so, MacPass does not support saving anything regarding autotype in a KDB file. I never came around to implement the feature as most people do not use KDB anymore and have moved to KDBX containers.

The runtime model stores everything but upon unlock, the database is read again and since there is no information stored, you will end up with the defaults. There where times when MacPass did warn users about data-loss on storage but that has been removed as being too obstrusive so I might actually have to re-enable some form of this warning again.

**Comment by 88-percent** [comment]
This was it!

I've been using KeePass for the better part of the last decade and I guess I never knew I needed to update the database. I transitioned to KDBX through the export command and now everything is working as it should. 

Thanks for your quick reply.
