### ISSUE TITLE
Remember open databases after launch

### ISSUE THREAD

**Issue by dschox** [MacPass/MacPass#1070]
**Is your feature request related to a problem? Please describe.**
If you have more than one database open (I always work with four DBs), after quitting and launching MacPass, only the last active database is reopened.

**Describe the solution you'd like**
I would love to have MacPass restore all my previous opened databases after launch.

**Describe alternatives you've considered**
There is the same issue reported here: https://github.com/MacPass/MacPass/issues/125
But I don't want enabling this macOS feature system wide because I generally dislike it.
I have seen some apps (can't remember which atm), that have dedicated checkbox in their preferences, to use the macOS Restore function independently of the the setting in system preferences. Maybe it could be implemented this way?

**Comment by mstarke** [comment]
If you let macOS handle the window state restoration, every database should re-open when you restart MacPass. However, if you have this disabled or use Quit and close all windows the MacPass internal solution is used which only stores the last database. It might be usefull to implent a way to re-open more than one database but since tabs are technically differnt windows this might be a bit chalenging. Also, I firstly search for the last opened databases via the system mechanics (recent documents that is) and choose the last on and based on this I have no real clue how many databases where open the last time.

**Comment by dschox** [comment]
ok, I understand. Thx for your reply!
I can live with the current state. I just select my four databases with cmd+click and then opening all at once with cmd+o
