### ISSUE TITLE
Adding Templates Not Working

### ISSUE THREAD

**Issue by ezekieldas** [MacPass/MacPass#1077]
**Describe the bug**

Docs describe a means to use templates but this isn't clear if template is based on previous entry or if it's possible to import a template. I am trying to use 'KP entry templates'

https://github.com/MacPass/MacPass/wiki/Templates
https://keepass.info/plugins.html#kpentrytemplates
https://github.com/mitchcapper/KPEntryTemplates

**To Reproduce**
I've followed instructions in MacPass documentation regarding templates. I've also followed instructions in KPEntryTemplates regarding installation. Neither offer results with 'create entry with' Is it possible this feature is missing 'On the "Add Entry" dialog, select the "Template" tab and click "Init As Template"'

**Expected behavior**
A means to use pre-defined templates

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - macOS: [e.g. 10.15.3]
 - Version [e.g. 0.7.12]

**Additional context**
n/a

**Comment by mstarke** [comment]
Templates are a standard feature of Keepass databases. KPEntryTemplates is a dedicated plugin and MacPass has no equivalent. If you want to use templates, you simply set a template group in the advanced database settings and then you are able to use entries inside this group as templates by clicking the arrow besides the plus button to add entry based on templates.

**Comment by mstarke** [comment]
Advanced settings for templates:
![Screenshot 2020-05-25 at 11 07 24](https://user-images.githubusercontent.com/58428/82797989-3030f380-9e78-11ea-8965-da32fb13424e.png)

Adding new entries via template:
![Screenshot 2020-05-25 at 11 08 47](https://user-images.githubusercontent.com/58428/82798148-6ff7db00-9e78-11ea-8f6b-fc1395540d77.png)


If you want to add an entry as template, simply create it in the templates group. The group is a normal database group, it's simply marked as special via the settings. Since MacPass does not offer a modal way to create entries, the "add as template" option is not present. It might be usefull to add the option below the create from template list in the context menu on the create button e.g. add new template entry or something similar

**Comment by F3000** [comment]
@mstarke  short question about templates : 

will you integrate templates for specific uses cases like “credit card” or do you want that only the user can creates templates ?

**Comment by mstarke** [comment]
I have currently no plan to integrate this but this might be a usefull place for plugins to allow for "custom" entry templates to be generated.

**Comment by mstarke** [comment]
Since this is more related to porting KPTemplates over to MacPass I'm closing this. If KPTemplates is needed, a new issue should be opened.
