### ISSUE TITLE
[Info] macOS Big Sur - no issues so far

### ISSUE THREAD

**Issue by georgesnow** [MacPass/MacPass#1087]
I tried MacPass on macOS 11. So far all the functionality seems to work. However, permission dialogs for Accessibility don't get triggered. I had to manually add MacPass, but that being said. This was true for 2 other apps I tested that require similar  permissions for Accessibility. Those didn't present the prompts in my initial testing.

so this is promising.   👍

Tested items:
Global Autotype
Autotype
AutotypeURL
Create new database
Add entries

**Comment by mstarke** [comment]
I've tested MacPass 0.7.12 on Apple Silicon in Rosetta2 and every toolbar button is disabled.
Re-building for Apple Silicon resolved the issue.

**Comment by georgesnow** [comment]
Apple has added the QuickType feature for macOS 11. This would be a good addition instead of safari extension. A few other iOS ports of KeePass support this feature and it is really nice. 


https://developer.apple.com/documentation/authenticationservices/ascredentialidentitystore

**Comment by xBytez** [comment]
Tested MacPass 0.7.12 on my 2019 16" MacBook Pro, I also experience here that every toolbar button is disabled including the search bar.

**Comment by capjan** [comment]
Same here on iMac (Retina 5K, 27-inch, 2017) with Big Sur Version 11.0 Beta (20A5323l)
All Toolbar buttons are disabled.

**Comment by xBytez** [comment]
Update, rebuilding from source as instructed in the README fixes the issue, looks like the toolbar issue has already been fixed just not released yet.

**Comment by mstarke** [comment]
@xBytez I raised the deployment target for 0.8 to 10.13 so the 10.15 SKD might have some issue on macOS 11.0 with a deployment target of 10.10. A did not have time to rebuild on intel and check with the current code.

**Comment by xBytez** [comment]
@mstarke I rebuild using Xcode 12 but didn't change any config. I cloned the repository and followed README instructions on how to be build.

**Comment by arnemoor** [comment]
@xBytez With Beta 6 of Big Sur and Xcode I already stuck at `carthage bootstrap --platform macOS` 

*** Checking out KeePassKit at "2.4.7"
*** Checking out HNHUi at "3.0"
*** Checking out Sparkle at "1.22.0"
*** Checking out KissXML at "5.3.1"
*** Checking out TransformerKit at "b28de3a7de9249dd886979cae4985092523b6dd1"
*** xcodebuild output can be found in /var/folders/1f/j2_861xd3n75_j88kwbdnqzh0000gn/T/carthage-xcodebuild.t1vEdV.log
*** Downloading KissXML.framework binary at "Version 5.3.1"
*** Downloading Sparkle.framework binary at "Many small improvements"
*** Building scheme "HNHUi" in HNHUi.xcodeproj
*** Building scheme "KeePassKit macOS" in KeePassKit.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/arm/sources-pub/MacPass/Carthage/Checkouts/KeePassKit/KeePassKit.xcodeproj -scheme KeePassKit\ macOS -configuration Release -derivedDataPath /Users/arm/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8189n/KeePassKit/2.4.7 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/1f/j2_861xd3n75_j88kwbdnqzh0000gn/T/KeePassKit SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/arm/sources-pub/MacPass/Carthage/Checkouts/KeePassKit)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/1f/j2_861xd3n75_j88kwbdnqzh0000gn/T/carthage-xcodebuild.t1vEdV.log

As far as I understand this is due to the fact that xcode automatically adds the arm64 architecture to the list of standard architectures for KeePassKit while KissXML does not provide that platform.

Any suggestion how to get the build succeed?

**Comment by mstarke** [comment]
I'll have to take a look into this since I have no x86 machine running the betas

**Comment by mstarke** [comment]
0.8 will raise the deployment target to 10.13. Using this build settings I was able to get MacPass to run without any issues on macOS Big Sur 11.0

**Comment by veasnalkj** [comment]
Since upgrading to Big Sur 11.0.1 (20B5022a), occasionally the search bar becomes unresponsive.  I've not been able to pin down when or how to reproduce it.  The only way I've found to work around it is to close and re-open that database.  Also, there is now an OS-level "Passwords" popup option that appears over top of the password box.  

<img width="298" alt="Screen Shot 2020-11-09 at 9 40 07 AM" src="https://user-images.githubusercontent.com/25754717/98569524-a632e680-226f-11eb-8b37-76c3411705c8.png">

**Comment by verhas** [comment]
After searching for something and then selecting one record, the top search bar becomes disabled and I have to exit and start again to perform the next search.

![image](https://user-images.githubusercontent.com/1597979/99040543-98d86d80-2589-11eb-9ad2-2ab4ab4a7a5c.png)

**Comment by mstarke** [comment]
I am about to release 0.8 by moving some planned features up to later versions to get a working release for macOS Big Sur. This should also include a native ARM version.

**Comment by ghufby** [comment]
> I am about to release 0.8 by moving some planned features up to later versions to get a working release for macOS Big Sur. This should also include a native ARM version.

Awesome!

In Big Sur I also have the problem of the toolbar becoming disabled after doing a search. Have to restart the app for the toolbar to become usable again. Looking forward to 0.8!

**Comment by error401de** [comment]
Hi everybody,
are there any news regarding the update? I need to press CMD+F 4-6 times until I get the search to work which is really frustrating :(

**Comment by mstarke** [comment]
The current continuous development build should run without any issues. I have to finish some things to be able to release it so it will take a couple of days at least until 0.8 is officially released.

**Comment by dmuiX** [comment]
How far is it? I have the same problems as described before: Search bar is not responding after first search. But the workaround with cmd + f is working so far.

**Comment by surmvoise** [comment]
Here's the issue with the search bar: https://github.com/MacPass/MacPass/issues/1152

**Comment by danpre** [comment]
I'm using MacPass 0.8-beta (20210115120112-continuous)
on Mac Big Sur 11.2.3
for a week now - 3 databases in use all the time

search bar works properly
all buttons are active

only one issue found:
when you search for something and get result
and then create new entry - focus in on wrong entry

**Comment by georgesnow** [comment]
@danpre  I have the same issue and it’s the same/similar behavior I reported in #1154

**Comment by mstarke** [comment]
@danpre #1154 is fixed
