### ISSUE TITLE
Copy type for Maccy

### ISSUE THREAD

**Issue by schwantuschke** [MacPass/MacPass#1095]
I use the clipboard manager Maccy and I want to ignore passwords from MacPass in Maccy.
For this I need the copy type from MacPass. How I find it?
[This is the documentation](https://github.com/p0deje/Maccy/blob/master/README.md#ignore-custom-copy-types) from Maccy.

**Comment by georgesnow** [comment]
I believe it is referring to the bundle ID:

com.hicknhacksoftware.MacPass

**Comment by schwantuschke** [comment]
> I believe it is referring to the bundle ID:
> 
> com.hicknhacksoftware.MacPass

This bundle ID works. Thank you :)

**Comment by schwantuschke** [comment]
> I believe it is referring to the bundle ID:
> 
> com.hicknhacksoftware.MacPass

This bundle ID works. Thank you :)

**Comment by schwantuschke** [comment]
The bundle ID dosn't work unfortunately. Maybe I need the bundle ID and a type?

**Comment by mstarke** [comment]
MacPass does not store any info on the pasteboard that you can rely on. This spoils be fixed ASAP. I’ve read about the special pasteboard types but never came around to implement them.

**Comment by georgesnow** [comment]
what's interesting there is way for apps to ignore based on apps. I only know that because I use Alfred's pasteboard manager. I just drag and dropped MacPass in the list and it ignores anything copied from MacPass. It does provide caveat about "focusable" apps. However, that would probably be something within Maccy that would provide that support. 

![image](https://user-images.githubusercontent.com/12751441/87075874-00069f80-c1ef-11ea-8a20-417cfffa6e6a.png)

**Comment by mstarke** [comment]
Since c759aeddd9ecf790a37c40425a1210d2f395c016 MacPass now sets concealed, transient and source values if apropriate
