### ISSUE TITLE
Changing master password for a database saved as key file locks the database

### ISSUE THREAD

**Issue by Sergserge** [MacPass/MacPass#1106]
When I wanted to change the master password I selected my only database as key file and saved. After that I can't open my database anymore.

1. Go to 'File>Change master password'
2. Enter new password and repeat new password
3. Key file>Choose..>Select the database file which is currently opened for changing the master password.

I tried to copy the same file and change file description for one in *.key format, and another to *.xml format and back to *.kdbx
So I try to open one as database and another as key file, but it doesn't work. Error "The password and/or the key file is wrong (1070)"

 - macOS: 10.15.6
 - MacPass Version: 0.7.9

I found it confusing to be able to save the database as key file when changing the master password and not being able to open it afterwards.
Is there still any way I can open my database?

**Comment by mstarke** [comment]
You are not the first one to fall into this trap. The ui for the password input screen has been changed to warn about kdbx files as key files. The change key UI does not have those warnings included ATM. This should be added ASAP.

You are not able to open your database because the keyfile (your database) has changed since the last save. The only way to get your file re-opened is to use a backup of your database from a state before you saved the changed master key.

**Comment by mstarke** [comment]
#1142 has been created to track this enhancement. Closing this.
