### ISSUE TITLE
Option to disable {ENTER} globally on Autotype

### ISSUE THREAD

**Issue by notoriousturtle** [MacPass/MacPass#1110]
**Is your feature request related to a problem? Please describe.**
Automatically submitting matched credentials is a security risk. 

I have way too many logins to manually go ahead and remove `{ENTER}` from them all. 

**Describe the solution you'd like**
An option to disable {ENTER} globally.

**Comment by mstarke** [comment]
Your solution is a bit more harsh since it might break sequences that use enter in-between.

The idea I was throwing around was re-working the multiple-match dialog for global auto-type to prominently show the application icon and the window title (or even a screenshot of the target window) auto-type is going to target. The dialog could be displayed even if only one match was found to add an additional check for the user to prevent anything being typed in the wrong window or even application.

**Comment by mstarke** [comment]
The current solution for this is the addition of "Always ask for confirmation when using global Autotype" in the integration settings. It is set to false by default and should be enabled in your case to allow for better control of what is typed where when Autotype finds a match.
