### ISSUE TITLE
Busy Cursor Randomly Interrupts Workflow

### ISSUE THREAD

**Issue by robbpriestley** [MacPass/MacPass#1132]
**Describe the bug**
Working in MacPass normally, entering data. Randomly the macOS busy cursor (spinning pinwheel) appears, locks the UI, and interrupts workflow. This clears after several seconds. Often if typing was still occurring during the lock, the buffered characters are spit into the text area that has focus.

**Expected behavior**
This could be related to auto-save? And I understand this feature is important, but there could be a better way of managing it than interrupting workflow?

**Desktop (please complete the following information):**
 - macOS
 - Version Big Sur

**Comment by mstarke** [comment]
Does this issue occur with the current continous release? You did not specify a version of MacPass.

**Comment by robbpriestley** [comment]
Yes, it does (0.7.12)

It has been an issue basically as long as I have been using the product (a year or two)

**Comment by mstarke** [comment]
So the issue is present under macOS 10.15 Catalina and did it did not start appearing on Big Sur?

Could you provide some statistics on your file: namely file size. Number of entries. Compression and Security settings (key derivation settings in particular). Does the file reside on the local disk or somewhere remote?

Thanks!

**Comment by robbpriestley** [comment]
Yeah for sure.

- Yes, the issue was already present under Catalina, I just did not report it until now.
- File size: 268 kb
- Compression: GZip
- Format: KDBX (version 3.1)
- Encryption: AES Rij
- Algorithm: AES
- Rounds: 75,000,000
- File resides locally

**Comment by mstarke** [comment]
MacPass currently does not allow for background-thread saves so this will block the ui until you db is saved. This is an issue that requires some more plumbing work since I need to be able to take a "snapshot" of the current tree and store to ensure no data corruption.

In your case did you consider reducint the rounds for the key transformation? It's a rather large number resulting in long save operations on all other clients as well. On mobile this might even be worse but I have no current figures on how fast the AES transformation works on mobile devices…

**Comment by robbpriestley** [comment]
I didn't consider reducing the rounds. Are not more round more secure?

My mobile device is performant when opening the database. I use a different client on iOS. It does not auto-save.

Perhaps I need to consider disabling the autosave in MacPass if it is not compatible with my workflow.

My suggestion for MacPass autosave would be: check for user input (key press, mouse click, etc). If there has been no input for some period of time (10 seconds?) then it is safe to auto-save. Else wait.

**Comment by mstarke** [comment]
The when and how of autosave are more or less up to the system and I would not consider tampering with this setup. It is possible to make this kind of checks but as stated above support for async save is the better fitting approach. You can however go full force and disable autosave altogether in the settings but this leaves you vulnerable to accidental data loss.

**Comment by robbpriestley** [comment]
OK, I guess this is not a real issue then. Thanks for your support and information.
