### ISSUE TITLE
`carthage bootstrap --platform macOS` failing locally on M2

### ISSUE THREAD

**Issue by vemv** [MacPass/MacPass#1234]
Hi, I'm trying to follow https://github.com/MacPass/MacPass/tree/cbb4cea9cfd697a97f800f51769fc619158ad4bf#how-to-build. I'm on M2.

In `carthage bootstrap --platform macOS`,  one step failed:

```
*** Checking out Sparkle at "1.27.1"
*** Checking out HNHUi at "6.0"
*** Checking out KissXML at "933f04fe5ad95c2be07ec0c2f801e140007f20fa"
*** Checking out KeePassKit at "3.2.1"
*** Checking out TransformerKit at "a8b5bb73cc327ec6798569b865c32fec5eb2289f"
*** xcodebuild output can be found in /var/folders/l4/4yzwhhj56zx9srjrzfb3frfc0000gn/T/carthage-xcodebuild.jAs8ZR.log
*** Downloading Sparkle binary at "Sparkle 1.27.1"
*** Building scheme "HNHUi" in HNHUi.xcodeproj
*** Building scheme "KissXML (macOS)" in KissXML.xcodeproj
*** Building scheme "KeePassKit macOS" in KeePassKit.xcodeproj
*** Building scheme "Sparkle" in Sparkle.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/me/MacPass/Carthage/Checkouts/Sparkle/Sparkle.xcodeproj -scheme Sparkle -configuration Release -derivedDataPath /Users/me/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/Sparkle/1.27.1 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/l4/4yzwhhj56zx9srjrzfb3frfc0000gn/T/Sparkle SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/me/MacPass/Carthage/Checkouts/Sparkle)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/l4/4yzwhhj56zx9srjrzfb3frfc0000gn/T/carthage-xcodebuild.jAs8ZR.log
```

[This](https://gist.githubusercontent.com/vemv/d8406ef5a865a5378cd4c837a9a23cde/raw/c6d04c82ab32c1c047cd67bc34b52f1394c72e12/gistfile1.txt) is the referenced log file. I cannot make sense of it.

Does this sound familiar?

Thanks - V

**Comment by mstarke** [comment]
I did a clean clone and build on my m1 mac and everything went through. Do you have the correct developer tools selected? If you have only one installation of Xcode at the default path try running this in the terminal before bootstrapping:

    sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

**Comment by mstarke** [comment]
Wait a minute. The culprit is here:

```
 Reason: tried: '/Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator' (no such file), '/Library/Frameworks/CoreSimulator.framework/Versions/A/CoreSimulator' (no such file), '/System/Library/Frameworks/CoreSimulator.framework/Versions/A/CoreSimulator' (no such file), NSBundlePath=/Applications/Xcode.app/Contents/Frameworks/AssetCatalogCocoaTouchKit.framework, NSLocalizedDescription=The bundle \U201cAssetCatalogCocoaTouchKit\U201d couldn\U2019t be loaded.
```

Somewho the CoreSimulator framework cannot be loaded. I'm unsure what this means in your setup, but it seems there's something wrong with your setup.

**Comment by georgesnow** [comment]
You could try uninstalling the command line tools and reinstalling them.

**Comment by mstarke** [comment]
@vemv were you able to build MacPass or does the issue still occur?

**Comment by arnemoor** [comment]
I have the same issue / error message today, my root cause was that I updated MacOS and then Xcode to 14.1.
Issue seem st be sparkle targeting an older OS version.

note: Building targets in dependency order
/Users/arne/sources/MacPass/Carthage/Checkouts/Sparkle/Sparkle.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.9, but the range of supported deployment target versions is 10.13 to 13.0.99. (in target 'bsdiff' from project 'Sparkle')
/Users/arne/sources/MacPass/Carthage/Checkouts/Sparkle/Sparkle.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.9, but the range of supported deployment target versions is 10.13 to 13.0.99. (in target 'ed25519' from project 'Sparkle')
/Users/arne/sources/MacPass/Carthage/Checkouts/Sparkle/Sparkle.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.9, but the range of supported deployment target versions is 10.13 to 13.0.99. (in target 'Sparkle' from project 'Sparkle')
warning: Run script build phase 'Run Script: Set Git Version Info' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Sparkle' from project 'Sparkle')
/Users/arne/sources/MacPass/Carthage/Checkouts/Sparkle/Sparkle.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.9, but the range of supported deployment target versions is 10.13 to 13.0.99. (in target 'fileop' from project 'Sparkle')
error: An empty identity is not valid when signing a binary for the product type 'Command-line Tool'. (in target 'fileop' from project 'Sparkle')
/Users/arne/sources/MacPass/Carthage/Checkouts/Sparkle/Sparkle.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.9, but the range of supported deployment target versions is 10.13 to 13.0.99. (in target 'Autoupdate' from project 'Sparkle')
warning: Run script build phase 'Run Script: Set Git Version Info' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Autoupdate' from project 'Sparkle')
** ARCHIVE FAILED **

**Comment by mstarke** [comment]
Well this marks the point where I need to update to sparkle two then :-)

**Comment by arnemoor** [comment]
@mstarke - Just verified today on my m1 machine that it now builds smoothly, following the simple steps in the main page. So I think this issue can be closed if @vemv has no veto. Thank you for upgrading to sparkle 2 :-)

**Comment by mstarke** [comment]
Thank you for the feedback!
