### ISSUE TITLE
Search by tag

### ISSUE THREAD

**Issue by rlbisbe** [MacPass/MacPass#201]
Currently search does not allow to search by tag. I may try to do it :)

**Comment by arvinsim** [comment]
Any update on this? I was surprised that this feature was not implemented.

**Comment by mstarke** [comment]
No update. But since tags are not at all well supported it's no surprise. I think this might get some attention soon as another high priority features are finally implemented.

**Comment by timkite** [comment]
I'll add another vote for search by tag. The official KeePass supports it, but KeePassX/CE does not (nor does MacPass). Oddly, MacPass is the easiest to use of the three for adding tags, putting them front and center in the inspector, but they're not super useful since they're not searchable.

Along with search by tag, a related suggestion would be, either in the menu or in a collapsible sub-section in the left sidebar (or even a separate pane on the bottom), show all tags with their entry counts. Clicking on each could then effectively be a saved search for just that tag. That would look and work much like Finder's tag support, fitting with the Mac native approach of MacPass.

**Comment by mstarke** [comment]
@timkite you idea about adding tags to the outline is something I tried as a small experiment but never quite finished. The idea was to actually save searches and add them just like "smart folders"

**Comment by mstarke** [comment]
Tags can be searched via the "Everywhere" setting in search. This is however now exculsive tag based search and Tags should get a special treatment.

@timkite your idea about the outline is already noted in #189

**Comment by DeX3** [comment]
> Tags can be searched via the "Everywhere" setting in search.

@mstarke Where is this "Everywhere" setting? I can't seem to find it?

I guess it should be in this search options bar part of the UI, but I don't see it here:
![Search options bar](https://i.imgur.com/PShHHiq.png)

**Comment by mstarke** [comment]
This is not present in 0.7.3. Will be released with 0.7.4
