### ISSUE TITLE
Reading "Plain Text" and "Rich Text Format" Attachments

### ISSUE THREAD

**Issue by Jimmyson** [MacPass/MacPass#326]
I have a key enteries in my database that have plaintext and RTF attachments. The KeePass application on Windows is able to open and edit these documents with the built it text editor, and is able to off-load the reading to an external program.

MacPass is unable to read my text attachment, and only offer to download them.
Would it be possible to get MacPass tell TextEdit (or the default Text Editor) to open and edit the attachments?

**Comment by mstarke** [comment]
If you enable QuickLook in the settings, you can also open the files in MacPass. This is however a security risk as I need to store the files openly for the Quicklook Daemon to be able to read them. The will be deleted when you close Quicklook or quit MacPass. But the files are there for everyone to read if someone watches the temporary folders. I was pondering with an internal editor/viewer but skipped that due to a rather low priority. Nonetheless it's a nice feature and surely worth implementing.
