### ISSUE TITLE
Focus should be set on result list when search is done

### ISSUE THREAD

**Issue by aliok** [MacPass/MacPass#414]
This is about UX.

Here is some process:
- Do `Cmd+F` 
- Type something
- Press `Enter`

Now, I need to use my mouse to select an item. Instead, it would be great if the focus is set on the first item of the list so that I can navigate with arrow keys and do `Cmd+Shift+C` etc.

**Comment by auge** [comment]
you can Cmd+Shift+E

**Comment by aliok** [comment]
For reference: `Cmd+Alt+E` worked. But still, just like we're used to it in other places, it is a much better UX with `Enter`.

**Comment by l3ender** [comment]
I agree with @aliok that it should focus automatically

**Comment by jeffmcneill** [comment]
See also #443 and #442 for more focus issues

**Comment by bwlang** [comment]
in case it's relevant, keepassX focus goes to the entry list after search.
Maybe down arrow instead of enter since the search is performed with each letter typed?

**Comment by willhardy** [comment]
I don't agree with @bwlang's "down arrow instead of enter", down arrow is not a valid alternative, the original suggestion from @aliok would be the better implementation for UX. Typing enter means, "I'm done typing my search, take me to the results".

I've managed to get a third of the way there by setting up an OS shortcut for this app, mapping Cmd+Enter to "Focus Entries", except that the first result still isn't selected, I still have to move my hands away from the home keys to the arrows to select the first entry before I can continue.

**Comment by mstarke** [comment]
Changed to the following:

* Enter in search moves to entries
* Down in search moves to entries
* Copy shortcuts work while in search on first hit in search
See #603 for details
