### ISSUE TITLE
[Feature Request] Remember secret key for a database file

### ISSUE THREAD

**Issue by rkubik** [MacPass/MacPass#508]
I have a few database files (work, personal, etc) and I use passwords and keys for both. When opening with MacPass I find that the key file is never preserved and I have to open Finder and navigate to it. Would be nice if the UI remembered what key was used last with a database file.

**Comment by mstarke** [comment]
Feature is already present:
![screen shot 2016-11-01 at 17 21 02](https://cloud.githubusercontent.com/assets/58428/19897233/937f44c8-a057-11e6-95d4-624a43baab35.png)

**Comment by rkubik** [comment]
I don't see it remembering the key file after opening DB and locking on 10.11.

<img width="781" alt="screen shot 2016-11-01 at 12 12 01 pm" src="https://cloud.githubusercontent.com/assets/927179/19901362/7c87cde2-a02c-11e6-8ba8-8b0e4f60dea0.png">

**Comment by mstarke** [comment]
Strange. What version are you running? Custom build or a binary release? My current quick test did work. Can you take a look what's written in the defaults via:
```bash
defaults read com.hicknhacksoftware.MacPass RememeberdKeysForDatabases
```

**Comment by rkubik** [comment]
0.6.2 alpha, binary release. 

>The domain/default pair of (/Users/<user>/Library/Preferences/com.hicknhacksoftware.MacPass, RememeberdKeysForDatabases) does not exist

**Comment by mstarke** [comment]
Strange. I'll try to hunt this down.

**Comment by nuudles** [comment]
@rkubik I think there was a typo in that defaults key. It should be:

`defaults read com.hicknhacksoftware.MacPass RememberKeyFilesForDatabases`

**Comment by mstarke** [comment]
Not really. Those are two different keys and I just realised I'm a typo-artist. Damn even the prefs are littered with them misspelled words!

`RememeberdKeysForDatabases`is dictionary mapping of: sha256(keyfile) : path/to/database
`RememberKeyFilesForDatabases` is a bool to enabled/disable the feature to store those mappings

**Comment by nuudles** [comment]
Oh.... fun with typos!

**Comment by bunducafe** [comment]
thanks for the hint. I was just about opening an issue with the new 0.76 version. After typing the password to open the MacPass I always used TAB + Spacebar in order to look for the Key-File. The TAB + Spacebar shortcut does not work anymore... so I am happy that the keyfile location also can be stored.

**Comment by mstarke** [comment]
@bunducafe Tabing into the key file selectoin and then hitting space opens the file dialog, so this should still work. What doesn't work is that space is opening the path control, but there you can only use space to select the Choose option and no file at all - or am I missing something?

**Comment by bunducafe** [comment]
@mstarke nope. On both machines (iMac and MacBook) I cannot hit tab+space to open the file dialog anymore. Hitting tab marks the password field blue instead of jumping to the next field.

**Comment by mstarke** [comment]
@bunducafe Damn. I have tab to all controls active so this slipped my setup. Setting it to only text-inputs you're right. Will have to fix this!

**Comment by bunducafe** [comment]
@mstarke no worries. I do a lot with they keyboard only that's why I was stumbling upon this one - even not realizing that I could store the location of the key file because of being too lazy to flip  through the preferences. In case someone is using more than one key file the shortcut will be very handy indeed.

**Comment by mstarke** [comment]
As I said, if you enable Tab Navigation for all controls in System Preferences > Keyboard > Shortcuts you can still use your tabs but you need to hit it twice since now you also can highlight the toggle button.
<img width="780" alt="Screenshot 2019-03-25 at 08 59 43" src="https://user-images.githubusercontent.com/58428/54903530-68d3e680-4edc-11e9-82d6-e18d24d17103.png">


I've created a separate issue #896

**Comment by bunducafe** [comment]
@mstarke Thanks a lot of the heads up. Indeed changing this to all controls does the trick now. I was completely unaware (again) that I could change the tab behaviour ;)
