### ISSUE TITLE
Clipboard is not flushed!

### ISSUE THREAD

**Issue by ryanthara** [MacPass/MacPass#516]
Maybe a small problem for mankind here on macOS Sierra, but maybe a big problem for the security os MacPass user.

The current version of MacPass (Version 0.6.2 (12420)) doesn't flush the pass phrases from the clipboard after the selected time passes by. The passphrase stay as till the next text copy operation in the clipboard.

<img width="512" alt="clipboard_flush" src="https://cloud.githubusercontent.com/assets/7117072/20661932/8715769e-b551-11e6-8f6a-08e7f1960b3b.png">

Is there anybody out there who can confirm this behaviour?

**Comment by mstarke** [comment]
I'll try to fix this ASAP. It even should be supported by a test scenario

**Comment by compuguy** [comment]
It seems to flush my clipboard after 30 seconds for me.

**Comment by mstarke** [comment]
I cannot reproduce your bug so I have no way of fixing this at the moment. If anyone else can check if this is happening it would be great. Furthermore could you try to take a look at the logs (Console.app) and see if anything is reported there from MacPass?

**Comment by mstarke** [comment]
Just out of curiosity - how do you copy the password? Do you use the MacPass command (Copy Passwort) or do you use the "Cmd+C" system shortcut? If you use the latter, MacPass does not clear the clipboard. MacPass only tries to clear stuff that was pasted by special command!

**Comment by mstarke** [comment]
I did start to implement a counter-badge displayed on the MacPass Icon until the Clipboard is cleared but that didn't work as expected so I scrapped it. It might actually be useful to re-add it since the user sees that MacPass is about to clear the clipboard. If the counter is missing the user knows MacPass will not clear anything. Currently you as the user have no clue if the clipboard is cleared, will be cleared or is just left alone.

**Comment by CauchyChe** [comment]
If I use the `Cmd + C` system shortcut to copy, Macpass would **NOT** clear my clipboard.
But when I use the MacPass command `Option + Cmd + C`, Macpass would clear my clipboard, it is fine.

**Comment by mstarke** [comment]
As I said earlier, the flushing is based only based on the content that was copied via the copy commands from the context menu. Copying text-content results in not flushing. This is a clear security risk and should be fixed. The best way would be to disallow the copy/paste behaviour directly inside a text view and delegate the actions to MacPass and then flush clipboard content.

**Comment by mstarke** [comment]
I've tinkered with a solution for this problem and I think it's more or less ready. What I've done is intercept all the copy commands from text inputs and make sure the get registers as clearable so MacPass knows it has to clean the clipboard. Will be available shortly.

**Comment by mstarke** [comment]
I've fixed the behavior. Will be pushed soon to continuous and made publicly available.

**Comment by 5minpause** [comment]
This is still open @mstarke ?

**Comment by mstarke** [comment]
As described above in https://github.com/MacPass/MacPass/issues/516#issuecomment-330961561 I've added clipboard clearing on all field in the entry inspector. A general rule is to look for the overlay. If the overlay is displayed when something was copied to the clipboard, the clipboard will then be flushed. If no display occurs, the content will not be purged after the timeout if MacPass is configured to clear the clipboard.

@5minpause The fix was published in 509d0c84b2b140c84af46c161a74bafebf684828 which was release with 0.7 so the fix is present for a while now. If you encounter any problems please open a new issue.
