### ISSUE TITLE
Keyfile "chooser" nees to be clicked twice

### ISSUE THREAD

**Issue by DominusExult** [MacPass/MacPass#54]
I'm not fond of needing to click twice on the choose field to choose the keyfile, maybe this can be made into a button.

**Comment by kud** [comment]
I've got the same problem.

When you choose not to save key files, it could be great that this input doesn't need to be clicked twice, indeed.

![2018-11-23 10-37-26 2018-11-23 10_37_44](https://user-images.githubusercontent.com/655838/48936916-b92a4000-ef0c-11e8-85b9-e2fcba6165f3.gif)

**Comment by mstarke** [comment]
I've came up with a changed version that doesn't require a double click in 3cf3e2515679cbd7d41f2f43c75dc2911befeb8d but I've encountered that you do not need a double click but instead could keep the mouse button pressed down and the menu will get activated as well.

This is however not necessary anymore since the choose dialog pops up just after you press "Choose" or use the space bar to pop up the menu.

**Comment by kud** [comment]
Great, thank you. :)
