### ISSUE TITLE
Easy way to find and install plugins

### ISSUE THREAD

**Issue by gagarine** [MacPass/MacPass#627]
Installing pluging like https://github.com/MacPass/MacPassHTTP is complicated and impossible for peoples without good computer skills.

Perhaps some plugin should be build with MacPass directly, so the user simply have to enable the one he want. Some can perhaps even be enable by default.

At least, in the plugin windows they should have a button "add a plugin" where the user can load a plugin he had downloaded.

**Comment by mstarke** [comment]
The complete plugin system is unfinished and this requires a lot of work on all sides.

- stable plugin API
- easy installation/deinstallation
- easy discovery (e.g. a plugin repository)

**Comment by mstarke** [comment]
As a side note, I was considering plugin installation via drag and drop and double-clicking the plugin but haven't been able to finish it. Double-Click installation (as done by other tools) is by far the easiest way but requires the plugin to be present in the first place, the "Install Plugins" action inside MacPass might be better for discoverability.

Bundled plugins are another thing that I considered but I skipped it since I wanted to focus on MacPass itself without also having a lot of side-projects as distractions.

**Comment by mstarke** [comment]
Add plugins button in plugin settings is present since 0.7.

A plugin repository has been started here: https://macpass.github.io/plugins

What's next:
- make MacPass aware of the page and offer "auto installs"
- support a plugin-version-checking system to ensure outdated plugins get updated
- prevent unsupported plugins from loading in MacPass

**Comment by mstarke** [comment]
Plugin browser is included in MacPass since some time now.

* ✅ stable plugin API
* ✅ easy installation/deinstallation
* ✅ easy discovery (e.g. a plugin repository)
