### ISSUE TITLE
Move this repository under https://github.com/MacPass

### ISSUE THREAD

**Issue by gagarine** [MacPass/MacPass#628]
Would be nice to have this repository under https://github.com/MacPass no?

Moving repository is not a big deal now as GitHub take care of redirections: https://github.com/blog/1508-repository-redirects-are-here

**Comment by mstarke** [comment]
Considered but results in the need to move/recreate the github project page and this is something I keep pushing along since I have no real idea and resources to actually do it right. There's a domain registered for MacPass as well (http://macpassapp.org) but this need to be tied together correctly until then I leave it as is for the sake of simplicity.

**Comment by mstarke** [comment]
Repository was moved quite a while ago so I consider this done.
