### ISSUE TITLE
Support for {PICKCHARS} placeholder

### ISSUE THREAD

**Issue by przemekd** [MacPass/MacPass#637]
I think that's the really big feature that MacPass currently lacks. See http://keepass.info/help/base/placeholders.html#pickchars.  Do you know how hard can it be to add it? May a person who has never programmed in Objective-C be able to help with it?

**Comment by mstarke** [comment]
The `{PICKCHARS}` command is a bit complex and I never used it so it wasn't high on my list of things to do. Implementing it is a bit more tricky since it requires UI Interaction, a rather complex option list to support and more so I would not advice to implement this as the first thing you want to do in Obj-C. If I find the time I'll look into adding it.

**Comment by mstarke** [comment]
Just a heads up. I'm onto adding this feature as it requires some nice changes to KeePassKit and the placeholder system. Currently the system works with the password input and no options are parsed but this should not take that much extra time.

**Comment by mstarke** [comment]
Current status:
<img width="428" alt="screen shot 2017-11-26 at 11 29 50" src="https://user-images.githubusercontent.com/58428/33239220-5e0a0f84-d29d-11e7-9d24-d2ffd3a65a44.png">

**Comment by mstarke** [comment]
Pickchars was added in 0.7.4 with some fixed in 0.7.10
