### ISSUE TITLE
Warn if plugins are outdated

### ISSUE THREAD

**Issue by Floppy** [MacPass/MacPass#703]
MacPass updated itself the other day, and I didn't realise the MacPassHTTP plugin needed updating too, until I finally realised why it had stopped working. After installing the Sep 25 version, it all works fine again. Would it be possible to notify users if their plugins are out of date somehow, or incompatible with the current version of MacPass?

**Comment by mstarke** [comment]
I try to warn people about changes in the release notes. A system to automatically detect plugin requirements and detect outdated version would be awesome but it requires quite some effort. I pondered about this and came up with a list of options.

### Break plugins compatibility with every update
This is an easy way but requires constant updates to any plugins which might run fine since nothing has changed. This is not bad at the moment since there's only on plugin for MacPass available at the moment which is even maintained by myself but this will kill any other (potential unmaintained) plugins rather rapidly

### Introduce versioned Plugin API
This requires a big effort to abstract internal structures away form the plugins since currently they can mess about and e.g. have to have access to KeePassKit directly wich might change with MacPass changes. This would be an awesome way since then the Plugin API could be highly abstracted but currently it's too much effort. Again - only one plugin exists ATM.

### Semantic Version Checking
This seems like a reasonable solution since checking is rather straight forward and easy to implement but it pollutes the versioning of MacPass. Any changes to internal plugins that break APIs will lead to a "mayor" change in MacPass but without any real user facing changes. That's no deal breaker but unfortunate.

**Comment by Floppy** [comment]
Would allowing plugins to somehow check and alert for their own updates help? Then at least it would remind the user to update when something did break.

But yes, I appreciate that there's only one plugin at the moment, so this is pretty low priority :)

**Comment by FerretDave** [comment]
Or just have the installer run a prompt suggesting "you should check and update any plugins to ensure compatibility" ? and/or add a method for plugins to check for updates themselves, and add this to the main 'check for updates' option ?

**Comment by mstarke** [comment]
If plugins incorporate a update system this should be handled by them internally, I would not got as far as to include a update framework for plugins. What would be feasible is a plugin repository or means for plugins to propagate their version and updates to MacPass to let it check for updates.

One mayor issue is that broken plugins can crash MacPass and this is highly unwanted behaviour. That's why my first idea was to use a very strick and conservative way (Xcode does the same if I recall correctly)

**Comment by Floppy** [comment]
The plugin repository and check is a good solution. For now it could just be a simple data file in https://github.com/MacPass/macpass.github.io. 👍

**Comment by gagarine** [comment]
Bundle major plugin in MacPass solve this issue for most users no?

**Comment by Morg42** [comment]
Maybe the API could implement a simple function call which causes the plugin to check its own version. Plugins residing in a repository could check themselves or signal to MacPass...

**Comment by mstarke** [comment]
0.7.4 contains the above system with a curated compatibilty list on macpassapp.org
