### ISSUE TITLE
[FeatureRequest] Settings Option for Opening Single Key-Files in Integrated View as Default

### ISSUE THREAD

**Issue by hugo4711** [MacPass/MacPass#705]
The integrated view (if you open multiple single files) is really great. It should be possible to open single files in integrated view as default instead of using the window menu to gather all singular files into one integrated view.

**Comment by mstarke** [comment]
This is a system setting. MacPass adheres the setting for tabs. This has change with 10.13 to be more "tab-affine" but since MacPass support 10.10 I cannot upgrade to this newer api. If you set the macOS to always open new files as tabs MacPass will do so as well. If you have set to fullscreen only or never, pressing alt while opening a file or creating a new database (with the menu) will use a tab instead of a new window.

**Comment by hugo4711** [comment]
Could you provide a Key-Shortcut for 'tab gathering'?

**Comment by hugo4711** [comment]
I managed to set up a short cut by myself using the 'keyboard' settings:

**Shortcuts > App Shortcuts > + : Program 'Mac Pass', 'Merge all Windows', CMD+M**

I think apple should provide a shortcut...

**Comment by mstarke** [comment]
I have to revise my comment about the behaviour. Tabbing behaviour can be set so MacPass uses tabs instead of windows even if the user defaults are different. This might be unwanted for some use cases but I guess it's the better default behaviour.

This is updated in master and continuous as well
