### ISSUE TITLE
[Feature Request] Cloud Sync (e.g WebDAV) and TOTP

### ISSUE THREAD

**Issue by McKorleone** [MacPass/MacPass#711]
As I used it on Windows a possibility for a WebDAV sync with Nextcloud and TOTP like KeeOTP would be nice.

**Comment by mstarke** [comment]
TOTP is upcoming. About synchronization: I have no plan to do anything for this since it should Ben possible to do this ok the file system level e.g. mount WebDAV drives. You should geb able to connect to WebDAV drives automatically: http://osxdaily.com/2012/05/04/automatically-connect-to-network-drive-mac-os-x/
