### ISSUE TITLE
Slow save of database ≈38mb

### ISSUE THREAD

**Issue by vakhosh** [MacPass/MacPass#730]
Hi,
First, I should say that this app is just awesome. I use it a lot for a long time.
But, time-after-time, as the database grows, saving works slower. For now, my database is ≈38MB (with some files in it) and saving takes 8-10 sec.

**MacPass**: Version 0.7.3 (20171128131121-continuous)
**OS**: macOS 10.13.2 (High Sierra)
**Hardware**: MacBook Pro Mid-2012: Core-i5, SSD Kingston HyperX Savage

**Comment by mstarke** [comment]
Thanks for the praise. You seem to store a lot of extra files in the database to get it to be this large. Saving the database with a lot of files is slow with the currently widely used 3.1 KDBX format.

Can you create a copy of you database and save it with the new KDBX format?
To do so, open the database and then go to ```File -> Database Settings``` and in the Security tab select Argon2 for the Key derivation. Then save the file again and check if your save times have improved. If so, you might want to move to the new format once it's widely supported. I also have more potential for optimisations but those are not high priority but might save a few seconds.

**Comment by vaxo** [comment]
With **Argon2** it took 4-5 sec.
Is it safe to use Aragon2 for my primary database?

**Comment by mstarke** [comment]
The Problem is you changed your format to KDBX 4 with this. The new format is currently only supported by the official KeePass , KyPass and KeeWeb. Others will get support eventually but it seems to take some time as there are a lot of ports, some of which might never get it. MacPass does support it as well but it's was added with 0.7 so there may be bugs related to this so make even more backups if you switch just to be on the save side.

**Comment by mstarke** [comment]
You seem to be using a lot of "large" binaries and KDBX 4 improved the storage of binaries dramatically. KDBX3.1 stores binaries as base64 encoded strings. KDBX4 stores them directly as binaries inside the database.

**Comment by vaxo** [comment]
Thanks for the explanation. That's very helpful. I'll try to keep database smaller 😄
