### ISSUE TITLE
cmd-c to copy password of selected entry

### ISSUE THREAD

**Issue by minusf** [MacPass/MacPass#749]
i am a long time keepassxc user and i am giving macpass a test run.
is there a way to make cmd-c copy the password of the selected entry?
i think it is the most used function in any password manager and i am baffled
by the more complicated keyboard shortcut to achieve this....

**Comment by mstarke** [comment]
MacOS allows the user to override or add shortcuts of an app. You can do so by opening the System Preferences and the navigate to Keyboard and select the Shortcuts tab. In the list at the bottom you can add custom shortcuts for apps by entering the menu item's title and your desired shortcut.

Why is the shortcut the way it is? It's historical. On introducing shortcuts I used `CMD + C`like KeePassX but I quickly ran into a platform specific problem: On macOS every text input support `CMD + C` which will "grab" the action if a text input has the focus. This created some confusion and lead to undesired behaviour and my quick solution was to use a non-clashing shortcut.

I have recently started to implement more logic for copy/pasting and better handling of text inputs since I need to intercept them to make the secure clipboard functional. In conjunction with this there might be some time to invest into a solution for simple copy/paste.

But there's also a valid point against ist. The normal behaviour of copy is to copy everything the user has selected. If you select and entry and hit Copy, I, as a novice user, would think the whole entry is copied and I can now paste it to another location/database. This behaviour is currently completely missing and might be added as well so there's a clash in what's the actual desired behaviour.

Your point on it's the common action to do is a valid one an the app should try to streamline common tasks so this might be a place to stray from the convention.

**Comment by minusf** [comment]
thanks for the explanation, closing.

i am not here to argue, but i am not sure that the expectation of `cmd-c` in programs dealing with abstract data structures (such as an "entry" in a password manager) is to copy the whole record, as it would be usable only to MacPass: for me `cmd-c`/`cmd-v` is about copying data between applications through the clipboard... a `duplicate` or `clone` custom action makes more sense to me, but that's just me.

**Comment by mstarke** [comment]
The rationale of copy for me is copy what is selected. If an entry is fully selected without a text input being focused which is the case if you just click on it my understanding of a bare copy command is to copy what's selected. If you select a folder you copy the folder if you select the folder, edit the name and selection is on the text and then you copy, you copy the selected text. Your point of making the clipboard the interface to work between applications is an interesting view which never occured to me but I would strongly argue that it's not the main usage. The Finder example works well to demonstrate this. You most of the time move the files you copied inside the Finder and do not paste them into other tools. Your point of using abstract data does not apply to files. Another example is a formatted Table in a word processor. The data is usable across applications even in it's styled form but I think a lot of uses of copy/paste happen inside the word processor and even inside the same document. The text document is however a very different representation of data than a simple table view of password entries. There drag and drop is a more apt interface at least for me. But this is surely different for other users. 

But as I said it might be useful to streamline use cases.

And indeed there is a functionality called duplicate that does exactly what you describe. The concept of copy/pasting doesn't have to replicate this behaviour.

You're critique is fine and your certainly not the first one and I have no problem with discussing those facts since otherwise there is no improvement. A main reason not to change them frequently is the noted possibility for users to change them as they wish. Including this inside the app isn't worth the hassle but might make it more discoverable (see for example Xcode and it's key-mapping settings also with some handy collision warnings). Nevertheless the goal should be to have a reasonable default and not just "a default" since most users do not know about the feature of system wide custom keyboard shortcuts.

And as I said, I do have to put some extra efforts into copy/pasting to make it work reliable if it's the exact same shortcut as the system default for copying.

**Comment by minusf** [comment]
we have to make a distinction between copy inside an app, and copy with the intention of crossing app boundaries. when you copy files in the finder, (normally) you invoke paste inside finder as well: application borders are not crossed.  but if you do `cmd-c` in the finder and `cmd-v` e.g. in terminal, surprise, you get the filename and not the file...

i am not debating that the clipboard should be "text only".  but not all `cmd-c` operations involve the clipboard as such, and i mean the "global" clipboard.  inside my application i can make `cmd-c` copy anything i want wether that copied data can be interpreted outside my app or not..

ultimately, the point of MacPass is however to cross app boundaries and i think the keepassxc decision is the correct one.


but anyway, i tried the preferences approach and it does not seem to be working...

<img width="409" alt="screen shot 2018-03-05 at 10 55 40" src="https://user-images.githubusercontent.com/3632883/36968829-02b49446-2064-11e8-9cbf-0f4a24e6864b.png">

maybe it does not work for context menus?  no idea.
in any case, if i can't change the shortcut, going back to keepassxc. muscle memory is strong...

**Comment by tflo** [comment]
> but anyway, i tried the preferences approach and it does not seem to be working...
> maybe it does not work for context menus? no idea.

Yes, I think we can’t assign shortcuts to items in the contextual menu.

The problem is that the Copy Password entry is missing in the Edit menu. If @mstarke added the command there it shouldn’t be a problem to assign a shortcut.

Otherwise you could always forward <kbd>⌘</kbd><kbd>C</kbd> to <kbd>⌥</kbd><kbd>⌘</kbd> <kbd>C</kbd> with the help of tools like [Keyboard Maestro](https://www.keyboardmaestro.com/main/) or [BetterTouchTool](https://www.boastr.net). Another way is via AppleScript; then wrap the script in a System Service and assign the shortcut to that Service.

**Comment by mstarke** [comment]
@tflo I have to counter this statement. You **can** override the shortcuts in the context menu. I did this myself a lot of the times to provide feedback for issues. The problems seems to be that the shortcut applied is already used by the copy menu item so this might be due to internal resolving mechanics.

I did however add an Item menu to the main menu so all the actions available in the actions/context menu are now availabe in the top menu as well and this might fix this issue. The main purpose was to expose copy/paste to the window without having to focus the entry list. This is important for being able to copy attributes after a search.

**Comment by tflo** [comment]
You are right, it works. It needed _several_ restarts of the app to make it work, that’s why I thought it was not possible. 

Not surprising, if I use <kbd>⌘</kbd><kbd>C</kbd> it will steel the <kbd>⌘</kbd><kbd>C</kbd> from the normal Copy. Unless I assign something different to the normal Copy:

![screen shot 2018-03-07 at 20 00 16-pty-fs8](https://user-images.githubusercontent.com/1410282/37112441-bc21d3c8-2242-11e8-8b7c-dd07132bab1b.png)

![screen shot 2018-03-07 at 20 00 26-pty-fs8](https://user-images.githubusercontent.com/1410282/37112452-c043e194-2242-11e8-8724-9df0d6c86f96.png)
