### ISSUE TITLE
[doc] Propose a good browser plugin for global autotype

### ISSUE THREAD

**Issue by gagarine** [MacPass/MacPass#776]
Global Autotype work very well when you install a plugin that inject the url of the website in the tab title. For Firefox I'm using https://addons.mozilla.org/en-US/firefox/addon/url-in-title/  (on github: https://github.com/cloutierjo/titleUrl/ )

Wouln't be nice for users to provide a similar good plugin for different browser? At best it should be the same plugin (web extension).

Perhaps, we can even propose to install a plugin in the settings of global Auto-type.

**Comment by mstarke** [comment]
This issue should be handled in the documentation. The default approach would be to tune your database so that it works with the title of the website without needing the URL. I see the benefit of venting the URL for a clear match but using the title works well for almost all of my use cases. The one's where it doesn't, the selection dialog pops up which slows down the process of filling the password a bit but is still very fast IMHO.

Documenting those plugins to allow others to decide what to do seems to be the better fit. I see that you already added a section to the documentation of [Autotype](https://github.com/MacPass/MacPass/wiki/Autotype) so I would consider this issue resolved
