### ISSUE TITLE
Insecure right click behavior

### ISSUE THREAD

**Issue by tallakt** [MacPass/MacPass#787]
When I right click the password field in order to copy the text, I am getting the option to search with the selected term. This exposes me to a risk of submitting my password by accident to external sites

**Comment by mstarke** [comment]
In the process of changing the behavior on secured password inputs I extended the context menu and encountered similar problems. Some menu entries were added after MacPass was notified about menus being displayed which lead to me not being able to prevent them. I need to investigate this further since the reported behavior I highly unwanted. I might not have found the correct API to prevent this.

**Comment by tallakt** [comment]
Im on version Version 0.7.3 (17830) btw...

**Comment by mstarke** [comment]
I have implemented a fragile approach to remove the menu. But i think there are more items on the list that should not be present for a textfield with sensitive data. I tend to think that maybe it's best to remove everything except cut/copy/paste this will then get rid of speech, grammar, text-expansion and many more. The only thing that I have not found a way to remove is the services menu (which then might contain another "search with google" option)

**Comment by tallakt** [comment]
Could you disable the menu and just have a copy to clipboard button?

**Comment by mstarke** [comment]
You mean like 1Password does it? The custom class for text fields used in MacPass supports something like this for ages but I never went on with it because of various usability and layout quirks that came along with using a single copy button. Furthermore this might break keyboarded shortcuts but I'm not 100% sure about that.

**Comment by gagarine** [comment]
#791 can fix part of that (when you are not editing).

**Comment by mstarke** [comment]
Current master does not show the services menu nor any other things that might vent the password. This is done by not allowing services in the text fields and removing any unwanted submenus from the context menu.
