### ISSUE TITLE
Clipboard issues

### ISSUE THREAD

**Issue by 6hardmod9** [MacPass/MacPass#799]
**Describe the bug**
From time to time it happens that usernames/passwords are not stored in the clipboard. I copy it by double clicking the entry and the "Username copied!" hint appears successfully but obviously it won't work.
The clipboard is not empty but it just has my last manual copied content in it.
Happens on both machines I use. After 4th or 5th try it works.

**To Reproduce**
Not reproducible but happens at least one time a day. 

**Desktop (please complete the following information):**
 - macOS: 10.13.4
 - Version 0.7.3

**Comment by mstarke** [comment]
There was an issue with clearing timers not being reset when new content was pasted to the clipboard.  This resulted in any new content being deleted quickly.

To reproduce you can try the following:
Take a look at the setting for clipboard clearing. (e.g. 30 seconds, the longer the easier to reproduce)
Copy something to the clipboard and wait a couple of seconds before the time would clear the clipboard (say 25 seconds) and then copy somything new. The new content will be cleared after the first timer hits (5 seconds in) and you will have only the content that was restored into the clipboard in there. This is fixed in continuous (5db3950) and will ship with 0.7.4.

**Comment by 6hardmod9** [comment]
Hi @mstarke ,
thanks for your answer!
Is there any plan when 0.7.4 will be released?
