### ISSUE TITLE
Provide a setting to toggle notifications on/off

### ISSUE THREAD

**Issue by flat235** [MacPass/MacPass#811]
**Is your feature request related to a problem? Please describe.**
My global notifications are full of messages from macpass, I loose the ability to see important notifications at a glance.

**Describe the solution you'd like**
I would like to have a setting for turning off notifications.

**Describe alternatives you've considered**
Alternatively more precise settings to select which kind of notifications to send would be even more usefull.

**Additional context**
Notifications are a nice feature and I am thankfull for all the work on this great software. However, if you need more arguments as to why too many notifications may be a bad idea, look here:
https://en.wikipedia.org/wiki/Alarm_fatigue
or watch some episodes of Air Crash Investigations or the like ;)

**Comment by mstarke** [comment]
Do you want MacPass to stop posting notifications? If so, is disabling this in the Notifications preferences not a viable option for you?

Or do you want MacPass to supply a detailed setting on what to notify about? If so this sort of defeats the purpose. Autotype matches might not need a notification but misses should be notified since it shows the user that something did happen but not as intended.

**Comment by flat235** [comment]
whoops, excuse me, didn't to look into the OSX settings, I just assumed any shown notification would go into the history, my bad.
Switching notifications to only show once, but not to spam the history is all I need.
