### ISSUE TITLE
Focus the group of found item

### ISSUE THREAD

**Issue by liminspace** [MacPass/MacPass#816]
I have a lot of groups (really big tree).
When I'm looking for items by using search it's not easy to find the group of found items.

So I think it would be nice to add an addition item in context menu like 'Show the group'.

Or select and scroll to the group of focused item in search result after click on it.

Searching by group name also will be a nice feature.

**Comment by 360fun** [comment]
Hi! :) I have the same need: maybe an "easy to implement" solution could be add an option in the contextual menu "show in tree view"!
Even quicker would be add a "double click on group" (displayed in the column) => "show in tree view" ;)

**Comment by liminspace** [comment]
@360fun I moved to keepassxc. It's great and has more useful features including this one.

**Comment by 360fun** [comment]
thanks but I love MacPass: I just want to improve it a bit! :)

**Comment by mstarke** [comment]
@liminspace KeepassXC has an awesome community and being the only real Linux client drives development further. I do not like the UI concept of the client and the lack of macOS-ness. E.g. no version support, no undo/redo system, no quick-look support which is why I did focus on those point when developing MacPass.

@360fun Thank you for loving MacPass. I've added the double click feature already and a more discoverable context-menu entry will be added as well in the upcoming release.

**Comment by 360fun** [comment]
Awesome 😃 ❤️

**Comment by mstarke** [comment]
Both context menu and double-click action on the group column are added in master.

**Comment by 360fun** [comment]
YEAH! 🌳
