### ISSUE TITLE
Clarify saving behavior when quitting without saving

### ISSUE THREAD

**Issue by eedrah** [MacPass/MacPass#866]
First, thanks for the great app!

**Describe the bug**
An edited database can be closed without prompt and reopening will keep those changes without showing an "edited" tag in the app header.

**To Reproduce**
1. Open a database
2. Edit an item (for example, unprotect a field).
3. Close the database
4. Reopen the database
5. See that the item is still unprotected, and there is not "edited" in the title of the app.

**Expected behavior**
Some options:
- Closing the app or window (cmd-q or cmd-w) will show a dialogue saying "do you want to save your changes?". Selecting no will discard all changes this session.

That is my preferred option, but there is also another:

- Closing works as normal, but when reopening, the title shows "edited" like it was just before you closed it.

**Desktop:**
 - macOS: 10.14.1
 - Version 0.7.3

**Comment by mstarke** [comment]
MacOS uses autosave to enable this sort of workflow, this is in line with every app on macOS so I do not tend to introduce custom behaviour. You do have a point about the edit state which is fixed in the current master and will be released with 0.7.4. You can try the continuous build and verify that the behaviour is as you would expect it. You can change this by using "Close all Windows and Quit" by pressing ```Alt + Cmd + Q``` to quit or change the behaviour in the General System Preferences.
<img width="780" alt="screenshot 2019-01-05 at 10 53 29" src="https://user-images.githubusercontent.com/58428/50723013-4057ff80-10d8-11e9-8cb2-3f930e937983.png">

**Comment by mstarke** [comment]
@eedrah does the issue still persist for you with 0.7.6?

Also, I added a setting to disable Autosave which will be released with 0.7.7.

**Comment by mstarke** [comment]
The edited label should not vanish in version >0.7.3 and in combination with the added setting to disable autosave this should be fixed.
