### ISSUE TITLE
{HMACOTP} Autotype 

### ISSUE THREAD

**Issue by georgesnow** [MacPass/MacPass#895]
curious if you are still thinking about adding this? if so how would you want it to work? (inline as describe below or only available via AutoType  both something else etc..)  

There seems to a standard in KeePass for 2 custom fields:

TOTP Seed
TOTP Settings

Now with these 2 fields you can generate an OTP code. i noticed in one of the iOS keepass apps i use. it auto detected those fields and shows inline the generate OTP code in the list view 
(username password --- OTPCode)
keepassXC recognizes those fields as well 

Anyway trying to decide if this something i might be able to contribute too. However, Obj-C and or Swift is a new area for me. i am not sure how far i will get...

**Comment by mstarke** [comment]
I'm not only thinking about it, I already implemented the core functionality in KeePassKit. Take a look at the test cases in [KPKTestOTP.m]( https://github.com/MacPass/KeePassKit/blob/master/KeePassKitTests/KPKTestOTP.m). There is still some tooling missing, e.g. base32 encoding to allow for all input formats that KeePass supports for HMACOTP. TOTP is also implemented since it's only a modified version of HMACOTP that uses the time slice to generate an index instead of counting it up for every use.

**Comment by georgesnow** [comment]
I figured you light I asked cause I saw the place holder in the wiki. I had not looked into your code but that’s awesome!

**Comment by thomassth** [comment]
Any update on the issue?
It seems the work is done but no one bothered to write it into the UI?

**Comment by mstarke** [comment]
Sorry. I've got a lot of work to do recently, adding some restrictions because of the current global situation didn't offer much free time to invest into MacPass. The feature is a upper one on the roadmap but it's going to take a while since there need to be some plumbing done first.

**Comment by mstarke** [comment]
The current continous release has support for HMACOTP.

**Comment by georgesnow** [comment]
oh yeah awesome!
