### ISSUE TITLE
Custom icons blured

### ISSUE THREAD

**Issue by Niko-CZ** [MacPass/MacPass#905]
Hello Michael,
I have database created by Keepass for Win. It was always strange visualiazation - all custom icons were blured:
![Icons_2](https://user-images.githubusercontent.com/44586336/55225813-8f6b8780-5224-11e9-847a-03451fa3dd53.png)
I thought this is "by design". But after I created new database (again with Keepas for Win) and copied several of the entries from database#1 I found that in MacPass they look like normal:
![Icons_1](https://user-images.githubusercontent.com/44586336/55225898-c2158000-5224-11e9-8dd2-82d5cf0e3f51.png)
Could you please check?
Also here another issue related to icons operation "Download Icon". I assume it requires first icon to be selected and then downloaded, but click will initiate operation of icon set for current entry.

Regards,
Nikolay

**Comment by mstarke** [comment]
MacPass until 0.7.3 and earlier did fade out the icons under 10.13 and 10.14. This is fixed since 0.7.4. If you database contains such icons, MacPass isnt able to recover them but if you open the database in e.g. KeePassXC and save it again it should be fixed.

About the download icon button: If you have a url set on the entry, MacPass will try to download a facicon.ico. The algorithm is rather simple and I will use a more sophisticated approach. If the download works, the icon is added to the grid view and you can select it. If anything goes wrong, the button gets a little warning icon. You do not have to set an icon first.

**Comment by mstarke** [comment]
See #779 for the Icon issue

**Comment by Niko-CZ** [comment]
Thanks for solution related to "blured" icons. 
Current "Download Icon" scenario IMHO too much complicated.

**Comment by mstarke** [comment]
What do you suggest? I was thinking about adding an empty icon that looks like a download symbol but didn't go with this solution in favour of the button

**Comment by mstarke** [comment]
Keeweb does it this way 
![Screenshot 2019-03-29 at 17 49 05](https://user-images.githubusercontent.com/58428/55248884-09af0280-524b-11e9-9e02-2476a4359d28.png)

**Comment by mstarke** [comment]
Feature request is moved to #907

**Comment by Niko-CZ** [comment]
> What do you suggest?
I like Windows app scenario:
1) open icons dialog
2) with single click choose icons to operate with
3) click on button ("Download Icon"/"Delete Icon") to perform mass-operation for selected icons
*in case one icon chosen - button "Set" is available.
*in the same time double - click will do fast "Set" for the focused icon

**Comment by mstarke** [comment]
Current setup:

To set an available icon:
1. Click on icon to open dialog.
2. Click on Icon sets icon for entry and closes dialog (That's what you describe with double click)

To revert to a default icon:
1. Click on icon to open dialog
2. Click on "Use Default" button sets default button and closes dialog

To use a new custom Icon (A):
1. Drag an image onto the icon of the item

To use a new custom Icon (B):
1. Click on icon to open dialog
2. Drag an image into the grid
3. select image to set icon and close dialog

To delete custom Icon (B):
1. Click on icon to open dialog
2. Right-click on icon and select delete to delete the icon

I have no idea how a "mass operate" can work to download icons inside the dialog, this would require a dedicated action (e.g. download all favicons in the file/edit menu)

The only reason I can think of to select more than one icon is when you want to mass-delete them, otherwise, why select more than one?

**Comment by Niko-CZ** [comment]
>>why select more than one?
yep. In case of:
1) mass delete
2) mass export

**Comment by mstarke** [comment]
You mass-delete custom icons? And how do you mass-export custom icons?

**Comment by CoderJason123** [comment]
@mstarke are you thinking of moving forward with at least some of this feature?  By the way, is there a a certain image size / resolution that is preferred so it does look nice?

**Comment by mstarke** [comment]
@CoderJason123 what specific feature are you referring to? I am still not really sure the current system is so bad it needs to be changed completely. If you are speaking about the faded icons, this should be fixed by opening and saving the database with another client (e.g. KeepassXC)

**Comment by georgesnow** [comment]
i would say mass import it would be helpful. I imported 3 CSV files and had to re-drag every icon back in 1 by 1. I noticed 50% of the time the icon view would reset and not show any custom icons i had entered without clicking another entry and going back. Over half the entries the download favicon didn't work cause of the site didn't have one.

**Comment by georgesnow** [comment]
or have a container location you can add to them more easily.

**Comment by CoderJason123** [comment]
@mstarke - no, nothing is bad at all, no rewrites!!!  my question was, the icon download or import from file feature.  That way I can change an icon like for general without having to create an entry to import it from, know what I mean?

**Comment by mstarke** [comment]
@CoderJason123 You do not need to create an entry to import custom icons. The current system requires you to click on an existing icon but since there is always a root group you can get to this dialog all the time. I guess it would be nice to have this also added as a separate icon browser that can be opened without having to use a group or entry as starting point. I'm closing this for now since the core issue is already fixed.
