### ISSUE TITLE
Database settings menu not stable

### ISSUE THREAD

**Issue by FrankKooij** [MacPass/MacPass#913]
The database settings menu is not stable in v0.7.7. When navigating through the various tabs, the tab contents overlap and the color of the active tab is not set properly.

![Schermafbeelding 2019-03-31 om 10 18 23](https://user-images.githubusercontent.com/11964893/55286647-dda49600-539e-11e9-9a5e-481ebbae3328.png)

**Comment by mstarke** [comment]
Nice one. Classic localization error since it's breaking the layout you get the described behaviour

**Comment by mstarke** [comment]
The issue is not present on my system (10.14) with the current dutch localization. Can you specify on which os you're seing this behaviour?

**Comment by FrankKooij** [comment]
macOS 10.13.4

**Comment by mstarke** [comment]
I've found the issue. The dutch string dictionay did not contain all necessary information so there was an assertion being raised under 10.13. 10.14 seems to cope differently with the missing information and simply does not display any text at all.

![Screenshot 2019-04-01 at 11 46 04](https://user-images.githubusercontent.com/58428/55318848-fc289100-5473-11e9-89b8-df7ac409493b.png)

The marked two values were empty. I suspect this was caused by a xliff import.
