### ISSUE TITLE
Not a bug - just question about master password change

### ISSUE THREAD

**Issue by CoderJason123** [MacPass/MacPass#926]
Hello.  I am using both a key file and a password.  I went to change my password, but I did not do anything with the key file.  When I went to log back in, there was not a match.  I have a back up....

Once you click change password, is the procedure that I should generate a new key file?  I apologize if I missed this basic concept.

Thank you

**Comment by CoderJason123** [comment]
I think the interface on "using with a key" is not as clear as it might be -- and this is part of my not understanding how the composite key works, and just not sure when you change password if you need a new key.  I did end up with a file I could not open, but a back up took care of it.  I'm going to close the issue as I think this is more on my side of the fence.  Thank you.

**Comment by mstarke** [comment]
The change password dialog opens blank so no data is pre-filled. This might be misleading if you have a key file as well as a password and might only want to change the password but keep the key file. In this case you need to set both password and key to only update the password or vice-versa. I do understand that this setup might be misleading. Additionally it might be useful to tell the user that the changes will only take effect on the next save. This is something that might confuse a lot of users since all other changes more or less take effect immediately.
