### ISSUE TITLE
take theirs or merge

### ISSUE THREAD

**Issue by CoderJason123** [MacPass/MacPass#929]
Read behavior on merge / looks great.  The scenario you describe is pretty close to mine, except more than 1 person shares the database, not that that matters.  Anyway, if I put in 3 entries and someone else puts in 5 entries, is a merge going to duplicate the whole db or it's pretty smart and can tell the actual merge entries?

I wondered if I should just "take theirs" - rather than merge. Either way, one of the two will work for me, not sure which one to pick.  Thank you kindly.

**Comment by mstarke** [comment]
Take theirs is not an option in your scenario since your unsaved changes will get lost since they aren't present in "their" database. I used this wording since it's common in version control setups.

You have to keep in mind that the file that is open might be different that the file on disk. So the merge always merges the changes into the open file. Those changes will be lost if the file is not saved again. Normally Autosave should take care of this.

Alice and Bob have the same Database open an it's synced (e.g. via Cloud).

1. Alice adds 3 entries
1. Bob adds 5 entries
1. Bobs file gets saved
1. Alice file gets updated with the changes from Bob (+5)
1. Alice's MacPass is detecting a change in the file outside of MacPass since the file was updated after it was loaded.
1. Alice chooses merge
1. Alice loaded file is missing the 5 entries, so those get added. The file now contains her 3 entries as well as Bob's 5 entries
1. Alice's MacPass wants to save the changes and tells Alice that the file on disk has changes since it was opened. Alice chooses save to overwrite the file with here merged file.
1. Alice's file gets saved
1. Bob's file gets updated with the merged changes from Alice
1. Bob's MacPass detects a file change outside of MacPass since the file was updated after it was loaded.
1. Bob chooses merge.
1. Bob's loaded file is missing the 3 entries from Alice. Those get added to Bob's loaded file. The other 5 where already present so no changes take place.

You can make this example more complicated, e.g. Bob changes the 5 entries after the get merged into Alice's file but those changes will get preserved.

The only edge case for a merge are changes taking place on the same entry after a save but those will get resolved by adding one of the edits into the history.
