### ISSUE TITLE
[Question] KeeShare support?

### ISSUE THREAD

**Issue by georgesnow** [MacPass/MacPass#931]
I noticed KeePassXC has added a new feature called "KeeShare". The feature allows Import/Export of specified entries from database. Is this something that has possibility of being supported in MacPass? Or only if someone decided to build plug-in?

**Comment by mstarke** [comment]
Hehe. KeeShare is a plugin developed by HicknHack Software which happens to be the same HicknHack Software I’m working at. The plugin is maintained by one of our employees and myself. I have currently no plans to add this feature to MacPass until some details are resolved. But when it’s done this is a nice plugin for MacPass as well since it’s requiring a lot of hooks (Custom icons, Custom Settings UI, Actions for Special items, Save and Load hooks, etc.). KeeShare does not have a plugin system instead all features are compiled into the app so they get better integration but I’m sure the plugin system is the way to go.

**Comment by georgesnow** [comment]
going to close this for now. if/when the details are resolved open a new issue about building a plugin
