### ISSUE TITLE
Is there an option or setting to not generate password when add NEW_ENTRY?

### ISSUE THREAD

**Issue by tangr** [MacPass/MacPass#984]
Hi,
    It there an option or setting globally not auto generate password when add new entry, then I can generate when needed, since I only mostly store my exist password.
   Thank you.

**Comment by mstarke** [comment]
There is no option for that. A workaround is to use Entry templates and uncheck "Update password for new entries" in the Workflow preferences.

Then, when you add an entry based on this template, the password will not be changed. You could use an empty password for the template and thus nothing get's generated.

I am a bit reluctant to eliminate this behaviour since it seems a rather edgy case and adding yet more preferences options is something I try not to do. There are too many already IMHO.
