### ISSUE TITLE
Add custom field button without options

### ISSUE THREAD

**Issue by ryanthara** [MacPass/MacPass#995]
**Describe the bug**
Arrow on the plus icon without function.

**To Reproduce**
1. Go to an entry, scroll down in the right part 
2. Click on the '+ arrow' button

**Expected behavior**
A context menu or options to choose.

**Screenshots**

<img width="264" alt="Bildschirmfoto 2019-11-01 um 06 28 56" src="https://user-images.githubusercontent.com/7117072/68004314-52132080-fc71-11e9-970d-d74edbec8683.png">

**Desktop (please complete the following information):**
 - macOS: 10.15.1
 - Version 0.7.10 (22740)

**Comment by mstarke** [comment]
The context menu is there since 0.7.4. It's purpose is to allow for custom extension via plugins to add special values. For MacPass the first use-case considered is to allow to add HMAC settings via a dedicated dialog. Since this isn't implemented fully the button has no menu. I did not add a way to hide the context button if nothing is present. I might disable it, if the menu is empty.
